
#the following are the config parameters written in TOML

[ build ]

#only uses the first one for now, will do multiprocessing later
HASH_TAG = ["#QANON","#BLM","#Cool"]
# placed inside a nested array, the relvent twitter keys are placed in this order
# consumer_key, consumer_secret , access_token , access_token_secret
#only uses 1 key for now.
API_KEYS = [
[ "DjIoNZUIgCFjWGwUqSK5URonu" ,"RSD0dzVW2ueIWhOsVvp2NBDBTCoOKqwlzpGIAl38GAsTBGHWZJ","1267900781480550400-eQfU9yqYrSAFa0NpHyldWAUdlWepkl","MVloTLzM4THjVCo87ELkoS0rSRL7agz6ppYDuFxzz0CI9"],
[ "Uy4VXXXXXXXXXXXXXXXXXXXXXXXXXXXX" ,"Ewt9jXXXXXXXXXXXXXXXXXXXXXXXX","1040877050XXXXXXXXXXXXXXXXXXXXXX","gM9TM4XXXXXXXXXXXXXXXXXXX"]
]

# Filers for the tweets.
start_date = "2020-01-01"
num_requested = 100000

# Notable users profile scrapper
# for notable users who meet some of these conditions scrape their entire profile going x months back
verified = true
notable_min_fav = 500
notable_min_followers = 10


